#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
OVERRIDES_PATH="$ROOT_DIR/CodexMobile/BuildSupport/PrivateOverrides.xcconfig"
PROJECT_PATH="$ROOT_DIR/CodexMobile/CodexMobile.xcodeproj"

TEAM_ID="${APPLE_TEAM_ID:-}"
BUNDLE_ID="${REMODEX_APP_BUNDLE_IDENTIFIER:-}"
CALLBACK_SCHEME="${PHODEX_CHATGPT_CALLBACK_SCHEME:-}"
OPEN_PROJECT="false"

POSITIONAL_ARGS=()
for arg in "$@"; do
  case "$arg" in
    --open)
      OPEN_PROJECT="true"
      ;;
    *)
      POSITIONAL_ARGS+=("$arg")
      ;;
  esac
done

if [[ ${#POSITIONAL_ARGS[@]} -ge 1 ]]; then
  TEAM_ID="${POSITIONAL_ARGS[0]}"
fi

if [[ ${#POSITIONAL_ARGS[@]} -ge 2 ]]; then
  BUNDLE_ID="${POSITIONAL_ARGS[1]}"
fi

if [[ ${#POSITIONAL_ARGS[@]} -ge 3 ]]; then
  CALLBACK_SCHEME="${POSITIONAL_ARGS[2]}"
fi

if [[ ${#POSITIONAL_ARGS[@]} -gt 3 ]]; then
  echo "[setup-ios] usage: ./scripts/setup-ios-personal-team.sh [TEAM_ID] [BUNDLE_ID] [CALLBACK_SCHEME] [--open]" >&2
  exit 1
fi

prompt_if_empty() {
  local prompt="$1"
  local current_value="$2"
  if [[ -n "$current_value" ]]; then
    printf '%s' "$current_value"
    return 0
  fi

  local response
  read -r -p "$prompt" response
  printf '%s' "$response"
}

prompt_with_default() {
  local prompt="$1"
  local current_value="$2"
  if [[ ! -t 0 ]]; then
    printf '%s' "$current_value"
    return 0
  fi

  local response
  read -r -p "$prompt [$current_value]: " response
  printf '%s' "${response:-$current_value}"
}

sanitize_slug() {
  printf '%s' "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | tr -cs 'a-z0-9' '-' \
    | sed -E 's/^-+//; s/-+$//; s/-{2,}/-/g'
}

TEAM_ID="$(prompt_if_empty 'Apple Team ID (10 chars, from Xcode > Settings > Accounts): ' "$TEAM_ID")"
if [[ ! "$TEAM_ID" =~ ^[A-Z0-9]{10}$ ]]; then
  echo "[setup-ios] invalid team id: $TEAM_ID" >&2
  echo "[setup-ios] expected a 10-character Apple team identifier such as ABCDE12345." >&2
  exit 1
fi

DEFAULT_SLUG="$(sanitize_slug "${USER:-local}")"
TEAM_SUFFIX="$(printf '%s' "$TEAM_ID" | tr '[:upper:]' '[:lower:]')"
DEFAULT_BUNDLE_ID="com.${DEFAULT_SLUG}.remodex.${TEAM_SUFFIX}.local"
BUNDLE_ID="${BUNDLE_ID:-$DEFAULT_BUNDLE_ID}"
BUNDLE_ID="$(prompt_with_default "Bundle identifier" "$BUNDLE_ID")"
if [[ ! "$BUNDLE_ID" =~ ^[A-Za-z0-9-]+(\.[A-Za-z0-9-]+)+$ ]]; then
  echo "[setup-ios] invalid bundle identifier: $BUNDLE_ID" >&2
  echo "[setup-ios] expected reverse-DNS style, for example com.tommy.remodex.p5m598f2h6.local." >&2
  exit 1
fi

DEFAULT_CALLBACK_SUFFIX="$(sanitize_slug "$BUNDLE_ID" | sed -E 's/^com-//; s/-local$//')"
DEFAULT_CALLBACK_SCHEME="phodex-${DEFAULT_CALLBACK_SUFFIX}"
CALLBACK_SCHEME="${CALLBACK_SCHEME:-$DEFAULT_CALLBACK_SCHEME}"
CALLBACK_SCHEME="$(prompt_with_default "Callback URL scheme" "$CALLBACK_SCHEME")"
if [[ ! "$CALLBACK_SCHEME" =~ ^[A-Za-z][A-Za-z0-9.+-]*$ ]]; then
  echo "[setup-ios] invalid callback scheme: $CALLBACK_SCHEME" >&2
  echo "[setup-ios] expected something like phodex-tommy-remodex-p5m598f2h6." >&2
  exit 1
fi

TEST_BUNDLE_ID="${BUNDLE_ID}.tests"
UI_TEST_BUNDLE_ID="${BUNDLE_ID}.uitests"

cat > "$OVERRIDES_PATH" <<EOF
// Generated by scripts/setup-ios-personal-team.sh
// Keep this file local. It is gitignored on purpose.

REMODEX_DEVELOPMENT_TEAM = $TEAM_ID
REMODEX_APP_BUNDLE_IDENTIFIER = $BUNDLE_ID
REMODEX_TEST_BUNDLE_IDENTIFIER = $TEST_BUNDLE_ID
REMODEX_UI_TEST_BUNDLE_IDENTIFIER = $UI_TEST_BUNDLE_ID
REMODEX_MENU_BAR_BUNDLE_IDENTIFIER = ${BUNDLE_ID}.menubar
REMODEX_CODE_SIGN_ENTITLEMENTS = CodexMobile/CodexMobilePersonal.entitlements
PHODEX_CHATGPT_CALLBACK_SCHEME = $CALLBACK_SCHEME
PHODEX_DEFAULT_RELAY_URL =
EOF

echo "[setup-ios] wrote $OVERRIDES_PATH"
echo "[setup-ios] team id: $TEAM_ID"
echo "[setup-ios] app bundle id: $BUNDLE_ID"
echo "[setup-ios] callback scheme: $CALLBACK_SCHEME"
echo
echo "Next steps:"
echo "1. Open $PROJECT_PATH"
echo "2. In Xcode, select the CodexMobile app target and your iPhone as the run destination."
echo "3. If Xcode prompts for Developer Mode or device trust, accept those prompts on the iPhone."
echo "4. Press Run."

if [[ "$OPEN_PROJECT" == "true" ]]; then
  open "$PROJECT_PATH"
fi
